### ISSUE TITLE
Inconsistent gas_overhead for relayed transaction

### ISSUE THREAD

**Issue by drortirosh** [tabookey/tabookey-gasless#108]
Currently, when the **RelayHub**  processes a transaction, the gas_overhead is not fixed: there is a small code that varies with actual relayed transaction size.

**EXPECTED RESULT**
the gas_overhead should be fixed (indeed, the tests overcome this problem by verifying the **rounded precentage**, since the actual price is not fixed..

**CAUSE**
AFTER calculation of the **charge**, the relay performs `keccak(encoded_function)`
This has 2 problems:
- the overhead is not fixed: it depends on the size of the transaction
- it is completely useless: the hash can't be used for anything, unless the same function is called twice, with the same parameters.
- This param should be replaced with the encoded function **selector**, which has *some* usefulness.

**Comment by shahafn** [comment]
Not sure why we need either. We can remove this param altogether.
