### ISSUE TITLE
Suggest that when requesting a signature, we tell users what they are signing

### ISSUE THREAD

**Issue by crazyrabbitLTC** [tabookey/tabookey-gasless#132]
As a suggestion, currently when we are using MetaMask as the tool signing the message, it looks very scary to the user- we are asked to sign something without any context what we are signing. 

It would be considerate if when using MetaMask we could tell users what they are signing and in particular tell them that no funds of theirs is at risk.

**Comment by drortirosh** [comment]
It would be very nice indeed, but it's not us, it's Metamask... It didn't let the app provide any message to the user. It only shows the actual data signed 
We _could_ reformat our message as a text, so in Metamask message  won't look that scary... However, it would still look like a long text (method call, with all 32byte called and addresses) and will require a lot of effort to parse the text into a transaction in the RelayHub - so effectively, we can't do anything about it .. sorry.
