### ISSUE TITLE
Conflicting Solc or Truffle versions

### ISSUE THREAD

**Issue by TrillCyborg** [tabookey/tabookey-gasless#145]
I'm getting this error and similar ones. I've been trying different truffle and solc version and I have not found a good way to fix this issue. It also happened in the `MetaCoin` contract.

Has anyone found a solution to this? Is there something I need to do not mentioned in the README?

```
Error: Error: CompileError: ParsedContract.sol:1:1: ParserError: Source file requires different compiler version (current compiler is 0.5.8+commit.23d335f2.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.17;
```

**Comment by nervehammer** [comment]
@TrillCyborg you need to update your contract to solidity 0.5.x. MetaCoin example is old you can try this contract https://github.com/SpringRole/smart-contracts-V2/tree/v0.5.x. Clone repo from tabookey's repo and build your docker image and run it. Change host URL to `localhost` in truffle.js. 
Install contract dep: `yarn`
Test contracts: `yarn test`
