### ISSUE TITLE
IRelayRecipient parameters

### ISSUE THREAD

**Issue by nventuro** [tabookey/tabookey-gasless#180]
The `IRelayRecipient` functions currently on `master` are currently lacking a couple of values that are required for them to be able to achieve their intended purposes.

For example, `acceptRelayedCall` doesn't receive `gasLimit` or `nonce`, both of which should be used in an acceptance scheme where `approvalData` contains a signature over relay parameters. If, on the other hand, the recipient intends to charge the user, `accept` should first check that they have enough balance, for which `gasLimit` is required.

Similarly, `pre` and `post` require both the `gasPrice` and `gasLimit` in order to compute charges.

Furthermore, it makes sense to forward the max possible recipient charge to `accept` and `pre`, since a) the hub needs to compute this value anyway (to check the recipient has enough balance), and b) the recipient would need to know about RelayHub's constants, gas stipends, etc., in order to calculate this value.

---

Additionally, I wanted to propose _removing_ some of the received values, for which we haven't thought of a use case yet, such as `relay` and `encodedFunction` in both `pre` and `post` (but leaving them in `accept`). If `maxPossibleCharge` is added to `pre`, we could also get rid of `gasLimit`, `gasPrice` and `transactionFee`. 

Removing these means not only a smaller and easier to understand recipient interface, but also gas savings: I measured total gas costs reductions of ~8k gas after reducing the interface to the proposed set shown below:

```solidity
function acceptRelayedCall(
  address relay, 
  address from, 
  bytes memory encodedFunction, 
  uint256 transactionFee, 
  uint256 gasPrice, 
  uint256 gasLimit, 
  uint256 nonce, 
  bytes memory signature, 
  bytes memory approvalData, 
  uint256 maxPossibleCharge
) public view returns(uint);

function preRelayedCall(
  address from, 
  uint256 maxPossibleCharge
) public returns (bytes32);

function postRelayedCall(
  address from,
  bool success, 
  uint256 actualCharge, 
  bytes32 preRetVal
) public;
```

**Comment by drortirosh** [comment]
> For example, `acceptRelayedCall` doesn't receive `gasLimit` or `nonce`, both of which should be used in an acceptance scheme where `approvalData` contains a signature over relay parameters. 
`approvalData` SHOULDNT sign the data. that's what `signature` is for (and actually, `signature` is redundant to ACR, since it was just checked in `canRelay`)

If, on the other hand, the recipient intends to charge the user, `accept` should first check that they have enough balance, for which `gasLimit` is required.
yes `gasLimit` is required (since `gasleft()` can't be called, yet)

> Similarly, `pre` and `post` require both the `gasPrice` and `gasLimit` in order to compute charges.
They need `gasPrice`, but since they are on-chain, they should use `gasleft()` instead of `gasLimit`

> Additionally, I wanted to propose _removing_ some of the received values, for which we haven't thought of a use case yet, such as `relay` and `encodedFunction` in both `pre` and `post` (but leaving them in `accept`).

I think that per-method charging as a business model: suppose accept free calls to "createAccount", but require charge for other operations.
The relay is there, since a dapp might have its own dedicated relay, which should let its own users get free meals, but would charge for foreign relays .

> If `maxPossibleCharge` is added to `pre`, we could also get rid of `gasLimit`, `gasPrice` and `transactionFee`.

interesting. need to think about it. 

in general, I thought of passing all parameters as a single `bytes` block.
it is structured and has a signature (e.g. eip-712)
this blob is passed as a single parameter to each method in the RR, each extracting the params it needs
a nice "side-effect" is that metamask will show the struct nicely when requesting a confirmation from the user...

**Comment by nventuro** [comment]
>`approvalData` SHOULDNT sign the data. that's what `signature` is for (and actually, `signature` is redundant to ACR, since it was just checked in `canRelay`)

Yes, agree regarding removing `signature` from there. To clarify, I was referring to an acceptance scheme where a recipient accepts relayed calls if their parameters were signed by a trusted party (e.g. the application's backend). 

>I think that per-method charging as a business model: suppose accept free calls to "createAccount", but require charge for other operations.

Having different charging behaviors based in the function selector is interesting. Would the rest of `encodedData` be required, or simply those four bytes?

>The relay is there, since a dapp might have its own dedicated relay, which should let its own users get free meals, but would charge for foreign relays .

I guess this could work, since the app would be paying to its own relay, though I'd imagine the user experience could become a bit weird.

>in general, I thought of passing all parameters as a single `bytes` block.
it is structured and has a signature (e.g. eip-712)
this blob is passed as a single parameter to each method in the RR, each extracting the params it needs
a nice "side-effect" is that metamask will show the struct nicely when requesting a confirmation from the user...

I was under the impression 712 and other signing-related EIPs (e.g. 191) were still under development, does MetaMask already support showing the data of each field when prompting for a signature? Anyway, since what the user signs are values to be sent to `RelayHub`, I'm not sure if the recipient interface would be affected by this.

I've also considered the blob approach, but it has the drawbacks of being very error prone and have a lot of gas overhead not only because extra data is sent, but also to encode/decode it.

**Comment by nventuro** [comment]
(sorry, I edited your comment by accident instead of replying! I edited it back to its original contents)

**Comment by drortirosh** [comment]
the `msg.data` is useful by ACR. There are scenarios where the method-sig is not enough, and deep look into the parameters is also needed, hence we added the `GsnUtils.getParams` methods.
(even though now I understand that `abi.decode` might be a better way, but it requires first slicing `msg.data` from its first 4 bytes..)

re: blob: using an EIP712-style message is not for the signing clarity, as I see the "ephemeral keys" a better way to go.
The reason I put it up is that they got a nice solution for doing typecheck.
I agree that it will require a full disclosure of the entire signed block with the RR, which is undesireable

**Comment by drortirosh** [comment]
Correction:
- the `gaslimit()` received by `pre`/`post` are not the actual transaction's limit. This means we do need to pass the gasLimit parameter to `accept`/`pre`/`post`.

The model I always have in mind:
I want to implement a RelayRecipient that charges the user's TOKEN to pay for gas.
- have a local method to calculate charge based on gas, gasPrice, txFee (and some external exchange rate of token-to-eth)
- `acceptRelayCall`: validates there is an approval, and that the user has enough tokens for entire gaslimit (including RelayHub's reserve)
- `preRelayedCall`: deduct from the user's balance the token price of the entire gaslimit)
- `postRelayedCall`: refund the user of the excess, based on actual gas used.

There are some possible simplifications for this model, but I want the RR model to be able to support this model.

**Comment by drortirosh** [comment]
**One more requirement:**
the RR must be able to "veto" requests which overcharge either txfee or gasprice: this is a case where the relay and client colluded against the dApp.
Of course, the dApp has no way to know the "real" low txfee, or "real" gas price, but
it might use some oracle which will give it a valid range for these value, to limit the possible attack.

**Comment by nventuro** [comment]
>The model I always have in mind:
I want to implement a RelayRecipient that charges the user's TOKEN to pay for gas.
    have a local method to calculate charge based on gas, gasPrice, txFee (and some external exchange rate of token-to-eth)
    acceptRelayCall: validates there is an approval, and that the user has enough tokens for entire gaslimit (including RelayHub's reserve)
    preRelayedCall: deduct from the user's balance the token price of the entire gaslimit)
    postRelayedCall: refund the user of the excess, based on actual gas used.
There are some possible simplifications for this model, but I want the RR model to be able to support this model.

Right, this is the same use case I want to support. The reason why I opted for simply passing `maxPossibleCharge` is to simplify the recipients: we'd otherwise have every single recipient doing error-prone math, which will include the relay fee multiplication (`(price * (100 + fee)) / 100`), relayhub's overheads and gas caps for each method, to compute a value _the relayhub has already calculated_.

This is how such model could look like (minus the `post` part):

```solidity
function acceptRelayedCall(address, address from, bytes calldata, uint256, uint256, uint256, uint256 maxCharge, bytes calldata) external view returns (uint256) {
    require(_token.balanceOf(from) > maxCharge && _token.allowance(from, address(this)) > maxCharge);
}

function preRelayedCall(address, address from, bytes calldata, uint256, uint256, uint256, uint256 maxCharge, bytes calldata) external returns (bytes32) {
    _token.transferFrom(from, address(this), maxCharge);
}
```

>One more requirement:
the RR must be able to "veto" requests which overcharge either txfee or gasprice: this is a case where the relay and client colluded against the dApp.
Of course, the dApp has no way to know the "real" low txfee, or "real" gas price, but
it might use some oracle which will give it a valid range for these value, to limit the possible attack.

The issue with this is, as you mentioned, the need for oracles, or hardcoding of fees or gas prices, which is very inflexible. I don't think the recipient should be concerned with this case, since it will in turn charge the user for the amount paid: whether this value was originated from a high gas price, a high transaction fee, or lots of gas spent, shouldn't really be the recipient's concern.

**Comment by drortirosh** [comment]
We're talking about 2 business models: one is too be able to charge the client for everything, and the other is to "sponsor" specific users.
For the former, the RR didn't care about had price/fee, since it turns everything over to the client, which should have checked these offchain
But for the other night, where the RR agrees to pay. In this case, it needs a way to "cap" the costs and about malicious access.

Even if we don't have dapps that need it today, we must support it.

So unfortunately, we need parameters to cover all cases.

**Comment by nventuro** [comment]
That logic would be place in `acceptRelayedCall` though, wouldn't it? So the proposed API should cover a 'sponsoring' use case just fine.

**Comment by drortirosh** [comment]
Yes, accept needs all parameters. But so do pre and post..
