### ISSUE TITLE
Handling large encodedFunction with acceptRelayedCall

### ISSUE THREAD

**Issue by drortirosh** [tabookey/tabookey-gasless#196]
## Current Status:

Currently, `acceptRelayedCall` always receive the entire `encodedFunction` parameter.
Depending on the "business model" of the RelayRecipient, it might ignore it completely , or do partial check on it (just the methodSig, or also some parameters.)
In most cases, it doesn't need the entire `encodedFunction` - but still, we pay for gas of this entire (possibly large) `bytes` parameter.

## Suggestion:

add (yet another) template method:
`function acceptRelayedCallParamSize() view return (uint32)`
which is called just before `acceptRelayedCall()`, decide how much data (in bytes) is required.
- It can return `0` if it doesn't need any of the data
- `4` means only the methodSig is required
- `20` if it cares about the first parameter
etc..

its default value would be `4`, since its a nice balance as not to pass too much (even if you don't use it at all), and still useful.

The important thing is that in extreme cases (e.g. very large param block), we don't pass it too much around.

**Comment by spalladino** [comment]
I'm not entirely sure that this extra call will actually help in reducing the overall gas cost in the average case, especially if [EIP2028](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2028.md) is close to be adopted in the next fork. Nevertheless, it's worth running a few tests to get some numbers, and know when a function like this is needed.

I'd schedule this after the current release, when we have a better understanding of the usage of the GSN.

**Comment by drortirosh** [comment]
apparently, not an issue. passing large parameters block between functions doesn't cost much.
