### ISSUE TITLE
[ASAP] It seems we found a bug, relayer tx got reverted for some reason

### ISSUE THREAD

**Issue by k06a** [tabookey/tabookey-gasless#213]
https://etherscan.io/tx/0x129bd2ad369f703975ab81cf297441b530caccf27559646b93a3b0239c14274a

**Comment by k06a** [comment]
```
require(initialGas >= SafeMath.sub(requiredGas(gasLimit), gasOverhead), "Not enough gasleft()");
```

**Comment by k06a** [comment]
Maybe switching to force relay will help?
```
getRelayAddressPing URL: https://mainnet-03.gsn.openzeppelin.org
getRelayAddressPing URL: https://mainnet1.ddns.tabookey.com
getRelayAddressPing URL: https://mainnet-02.gsn.openzeppelin.org
race finished with a champion: https://mainnet1.ddns.tabookey.com
```

**Comment by k06a** [comment]
Increase `gasLimit` for at least 1k gas inside relayer!

**Comment by drortirosh** [comment]
Indeed, seems like a bug in gas calculation, which cause the relay to allot too little.
BTW: how did get the actual source line and values where it was rejected?

**Comment by k06a** [comment]
@drortirosh, I used remix debugger, but since source code mapping not worked I was made to look at assembly, found PUSH20 with hex encoded failure reason a few instructions before REVERT and checked stack state on comparison instruction.

**Comment by shahafn** [comment]
Seems to me that the size of the encodedFunction might be responsible for that, as it's not static and changes the required gas limit of the tx. So I added a fix to the server in #215 as per the yellowpaper, appendix G:
```
Gtxdatazero4    Paid for every zero byte of data or code for a transaction.
Gtxdatanonzero68    Paid for every non-zero byte of data or code for a transaction
```

**Comment by shahafn** [comment]
Fixed & merged to master.

**Comment by k06a** [comment]
@shahafn when you will deploy so I will be able to check if it works for the same previously failing transactions?

**Comment by drortirosh** [comment]
It is deployed to our relay, which is one of the 3 relays. 
running `./scripts/gsn-stats mainnet` will show you one relay is runing version 0.4.1
The tricky part is forcing your client to use it:
you should add `calculateRelayScore` option when creating your `RelayProvider`, to ignore the other relays. Unfortunately, the version string itself is not visible, so you need to filter by URL or by address.

```
calculateRelayScore = (relay) => relay.relayUrl.indexOf('tabookey') != -1 ? 1 : null
```

Highest score are accessed first. "null" score is filtered out completely.

**Comment by k06a** [comment]
@drortirosh cool, tx just successed: https://etherscan.io/tx/0xf3061ec4ee2e3fabd82b7dd784fcb580591a7dffaccacebb9383b532efd5403d
