### ISSUE TITLE
RegistrationBlockRate not configurable

### ISSUE THREAD

**Issue by EnchanterIO** [tabookey/tabookey-gasless#224]
Hey TabooKey team,

The `RegistrationBlockRate` is broken. Passing value as argument doesn't work. In order to fix it, remove this line: https://github.com/tabookey/tabookey-gasless/blob/master/server/src/relay/RelayHttpServer.go#L181 

and replace it with: 

```go
flag.Uint64Var(&RegistrationBlockRate, "RegistrationBlockRate", 6000-200, "Relay registeration rate (in blocks)")
```

That will solve the issue.

PS: Global variables are evil :)

**Comment by shahafn** [comment]
Thank you!
