### ISSUE TITLE
Relay with remote Ethereum node

### ISSUE THREAD

**Issue by deacix** [tabookey/tabookey-gasless#225]
Hi everyone!
Did i understood it right, that the relay can only work with a local Ethereum node?

If yes, why?
If no, where is the documentation?

Sergej

**Comment by drortirosh** [comment]
Indeed, we should document better the Relay configuration
A relay is configured with a node URL, which can be a local relay, infura URL, etc.
Here's a doc on bringing up a relay: https://gist.github.com/spalladino/f516b46bdefb5e025c5d28daf7ad1491

**Comment by deacix** [comment]
> Indeed, we should document better the Relay configuration
> A relay is configured with a node URL, which can be a local relay, infura URL, etc.
> Here's a doc on bringing up a relay: https://gist.github.com/spalladino/f516b46bdefb5e025c5d28daf7ad1491

Hey! Thans for fast reply! 
Where i should store my private key?

**Comment by deacix** [comment]
> the private key is saved as a file on the local file system.
> it is your responsibility that no-one will have access to the local storage of your relay machine...

Hi! Which location exactly? How can I change it? Which environment variable or how?

**Comment by shahafn** [comment]
It is saved under  `{Workdir}/keystore` directory, where `Workdir` is a flag given to the server by command line `-Workdir`

**Comment by deacix** [comment]
> It is saved under `{Workdir}/keystore` directory, where `Workdir` is a flag given to the server by command line `-Workdir`

Cool! Thanks! Is is somewhere documented?
