### ISSUE TITLE
relay: persistent transaction management

### ISSUE THREAD

**Issue by drortirosh** [tabookey/tabookey-gasless#77]
Relay should:

- Save all sent (pending) transactions.
- Remove transactions as they are mined.
- When a relay process is started, check if there are pending transaction (more than X minutes)
- re-send such pending transaction, with boosted gas price (e.g. eth.gasPrice*1.5)
Rationale: if a transaction blocks the relay (even if it agreed for a given gas price), it blocks the relay from processing new transactions, so it's better to boost it, even if it's on its own expense.

**Comment by drortirosh** [comment]
since we're already using geth sources (for abigen), this DB should probably use leveldb..

**Comment by spalladino** [comment]
I've started working on this one, hope to have something ready by early next week.
