### ISSUE TITLE
RelayHttpServer failed to get stake, stuck on waiting for stake 

### ISSUE THREAD

**Issue by nervehammer** [tabookey/tabookey-gasless#87]
I already deployed a RelayHub for goerli network at address [0xfe7ec2db12986896e1de65eac210a7015eb816cb](https://blockscout.com/eth/goerli/address/0xfe7ec2db12986896e1de65eac210a7015eb816cb/contracts). Added stake and register the relay node, also relay was added and the event was emitted for the same. 
I build a RelayHttpServer using `make build-server` and ran it using `./build/server/bin/RelayHttpServer -RelayHubAddress 0xfe7ec2db12986896e1de65eac210a7015eb816cb -EthereumNodeUrl "https://goerli.blockscout.com"`. But it is stuck and still waiting for stake with the following errors:

nervehammer@relayserver:~/tabookey-gasless$ ./build/server/bin/RelayHttpServer -RelayHubAddress 0xfe7ec2db12986896e1de65eac210a7015eb816cb -EthereumNodeUrl "https://goerli.blockscout.com"
2019/03/25 17:01:41 RelayHttpServer.go:40: RelayHttpServer starting. version: 0.3.5
2019/03/25 17:01:41 RelayHttpServer.go:239: Using default published port given in url: 
2019/03/25 17:01:41 RelayHttpServer.go:255: Using RelayHub address: 0xfe7EC2db12986896E1de65eAc210A7015eB816cb
2019/03/25 17:01:41 RelayHttpServer.go:256: Using workdir: /home/nervehammer/tabookey-gasless/build/server
2019/03/25 17:01:41 RelayHttpServer.go:257: shortsleep?  false
2019/03/25 17:01:41 RelayHttpServer.go:264: Constructing relay server in url  http://localhost:8090
2019/03/25 17:01:41 utils.go:40: ks accounts len 1
2019/03/25 17:01:41 utils.go:66: key extracted. addr: 0xC27129680f17787061A03CEfEF37E52ef4a0Cf3A
2019/03/25 17:01:41 RelayHttpServer.go:266: relay server address:  0xC27129680f17787061A03CEfEF37E52ef4a0Cf3A
2019/03/25 17:01:41 RelayHttpServer.go:60: RelayHttpServer started.Listening on port:  8090
2019/03/25 17:01:41 relay_server.go:350: abi: cannot marshal in to go type: length insufficient 64 require 96
2019/03/25 17:01:41 RelayHttpServer.go:326: abi: cannot marshal in to go type: length insufficient 64 require 96
2019/03/25 17:01:41 RelayHttpServer.go:329: Waiting for stake...
2019/03/25 17:01:41 relay_server.go:350: abi: cannot marshal in to go type: length insufficient 64 require 96
2019/03/25 17:01:41 RelayHttpServer.go:326: abi: cannot marshal in to go type: length insufficient 64 require 96
2019/03/25 17:01:41 RelayHttpServer.go:329: Waiting for stake...

**Comment by drortirosh** [comment]
You're using incompatible versions of relay and RelayHub.
The docker image (tabookey/dockerlay) which is used by the startup script was built against version v0.3.1 of the RelayHub.

you should **EITHER**:
1. checkout v0.3.1 of RelayHub, deploy it and use docker image from docker.io
**OR**
2. checkout latest (master) RelayHub, and rebuild the docker image (that matches it) before running it.
    to build the docker image, run `prodserverdock/build` . it will build **locally** the docker image.
    You can't push it to docker.io, of course, but you can use it locally, and it should work against your relay.

**Comment by nervehammer** [comment]
@drortirosh thanks it's working fine now. Just checked out to server-0.3.1 tag, `make build-server` and ran it normally.
