### ISSUE TITLE
Invalid json [] when making relayed transaction.

### ISSUE THREAD

**Issue by Kyrrui** [tabookey/tabookey-gasless#88]
I have been working on adding relayed transactions to a [Zepkit tutorial](https://github.com/zeppelinos/zepkit/pull/6). The relayed transaction works as expected, but throws an error in the logs. 

`MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: "Internal JSON-RPC error."}
`
and the relayer throws this in its logs:
`2019/03/26 16:04:35 RelayHttpServer.go:185: Invalid json [] unexpected end of JSON input`

I followed along the steps [here](https://medium.com/tabookey/how-to-make-your-dapp-gasless-da15d4d3cacd) to implement Tabookey's relayed transactions.

It is throwing an error at these lines.
<img width="570" alt="Screen Shot 2019-03-26 at 6 30 06 PM" src="https://user-images.githubusercontent.com/8539426/55094623-1c7bd880-508d-11e9-9fe3-dc17d6d2eb79.png">

**Comment by shahafn** [comment]
Zepkit tutorial doesn't work "as is" when cloning your repo, I get npm & truffle errors, can you help reproduce this bug?
