### ISSUE TITLE
Consider using camelCase instead of snake_case for external methods

### ISSUE THREAD

**Issue by spalladino** [tabookey/tabookey-gasless#89]
Given that the GSN is aimed to be [standardized as an EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1613.md), it would be good for its interface to conform to the style guides that apply for both [Solidity](https://solidity.readthedocs.io/en/v0.5.7/style-guide.html#function-names) and [Vyper](https://github.com/ethereum/vyper/pull/1055). In particular, all functions should follow `camelCase` (also known as `mixedCase`) instead of `snake_case`. Also, all current standards (such as ERC20 or ERC721) follow this convention.

This would mean changing all function names, such as `accept_relayed_call` to `acceptRelayedCall`.

**Comment by crazyrabbitLTC** [comment]
I would second that.

**Comment by shahafn** [comment]
See #113
