### ISSUE TITLE
Launch relay-server locally

### ISSUE THREAD

**Issue by svetlanama** [tabookey/tabookey-gasless#97]
Hello,

I have one question is there a possibility to launch a relay-server on docker from the local directory (not from the https://hub.docker.com/r/tabookey/gsn-dev-server).

**Comment by dtr2** [comment]
There is a `restart-relay.sh` script, which does just that - it builds the server, runs ganache and a relay.
It does have several prerequisites, such as ganache, truffle, go - which the docker image doesn't have.

**Comment by svetlanama** [comment]
Thank you, trying to call ```./restart-relay.sh``` I get an error:
```
abigen --sol ../contracts/RelayHub.sol --pkg librelay  --out /Users/..../tabookey-gasless/server/../build/server/src/gen/librelay/relay_hub_sol.go
make: abigen: No such file or directory
make: *** [/Users/..../tabookey-gasless/server/../build/server/src/gen/librelay/relay_hub_sol.go] Error 1
onexit
```
What can be the reason of it?

**Comment by drortirosh** [comment]
I forgot to add you also need ethereum source and solc. You can look at the complete list in ./dock/Dockerfile 
(Abigen is a compiler in go and is part of the geth source tree)

That's why we created the docker image, so you don't need to install everything...

**Comment by svetlanama** [comment]
Thank you very much!
